# Generated by Django 2.1.2 on 2018-10-05 06:20

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('id_number', models.CharField(max_length=10, unique=True, verbose_name='identity number')),
                ('country_code', models.CharField(default='233', max_length=4, verbose_name='country code')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='phone number')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('user_type', models.CharField(choices=[('M', 'Merchant'), ('E', 'Extension'), ('G', 'Goonacredit')], default='G', max_length=1, verbose_name='user type')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('verification_pin', models.IntegerField(blank=True, null=True)),
                ('verification_tries', models.PositiveSmallIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            managers=[
                ('objects', accounts.models.NewManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=30)),
                ('role_description', models.TextField(blank=True, help_text='Description of extension role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(blank=True, max_length=20, verbose_name='family name')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('other_name', models.CharField(blank=True, max_length=30, verbose_name='other name')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('phone', models.TextField(blank=True, verbose_name='phone number')),
                ('family_size', models.SmallIntegerField(blank=True, verbose_name='family size')),
                ('farm_location', models.TextField(blank=True, verbose_name='farm location description')),
                ('farm_size', models.IntegerField(default=0, verbose_name='farm size')),
                ('credit_rating', models.SmallIntegerField(verbose_name='credit rating')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='farmers/photos', verbose_name='photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, help_text='Product or Service provided', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of product or service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
