# Generated by Django 2.1.2 on 2018-10-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181008_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('family_size', models.SmallIntegerField(blank=True, verbose_name='family size')),
                ('farm_location', models.TextField(blank=True, verbose_name='farm location description')),
                ('farm_size', models.IntegerField(default=0, verbose_name='farm size')),
                ('credit_rating', models.SmallIntegerField(verbose_name='credit rating')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='farmers/photos', verbose_name='photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('M', 'Merchant'), ('E', 'Extension'), ('G', 'Goonacredit'), ('F', 'Farmer')], default='F', max_length=1, verbose_name='user type'),
        ),
    ]
