# Generated by Django 2.1.2 on 2018-10-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181009_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='farm_location',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='farm_size',
        ),
    ]
