# Generated by Django 2.1.2 on 2018-10-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181009_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_created',
            field=models.BooleanField(default=False, verbose_name='Profile status'),
        ),
    ]
