# Generated by Django 2.1.2 on 2018-10-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181009_1535'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='owner_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='accounts.FarmerProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offering',
            name='owner_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='accounts.MerchantProfile'),
            preserve_default=False,
        ),
    ]
